// Command shutdowner serves a password-protected web UI for remotely shutting
// down, restarting, sleeping and hibernating the machine it runs on.
package main

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"time"

	"shutdowner/internal/action"
	"shutdowner/internal/auth"
	"shutdowner/internal/config"
	"shutdowner/internal/logging"
	"shutdowner/internal/power"
	"shutdowner/internal/web"
	"shutdowner/internal/winsvc"
)

var (
	flagConfig          = flag.String("config", "", "path to .env (default: beside the executable)")
	flagConsole         = flag.Bool("console", false, "log to stdout instead of the log file")
	flagFakePower       = flag.Bool("fake-power", false, "development: log actions instead of executing them")
	flagAllowPublicBind = flag.Bool("allow-public-bind", false, "permit a non-loopback listen address")
	flagInit            = flag.Bool("init", false, "write a starter .env and exit; refuses to overwrite")
	flagHashPassword    = flag.Bool("hash-password", false, "prompt for a password, print its hash, and exit")
	flagInstall         = flag.Bool("install-service", false, "install the Windows service and exit")
	flagUninstall       = flag.Bool("uninstall-service", false, "remove the Windows service and exit")
)

const minPasswordLength = 12

const starterEnv = `# Generate with: shutdowner.exe --hash-password
SHUTDOWNER_PASSWORD_HASH=

# Generated by --init. Changing it signs every device out.
SHUTDOWNER_SESSION_SECRET=%s

# Must be a loopback address unless --allow-public-bind is passed.
SHUTDOWNER_LISTEN=127.0.0.1:8080

# Seconds between confirming an action and executing it. 0-3600.
SHUTDOWNER_DELAY_SECONDS=45

# How long a login lasts.
SHUTDOWNER_SESSION_TTL=168h

# Defaults to shutdowner.log beside the executable.
SHUTDOWNER_LOG_FILE=
`

func main() {
	flag.Parse()
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "shutdowner:", err)
		// A service that dies at startup has no console, so the event log is
		// the only place this becomes visible.
		winsvc.ReportError("shutdowner failed to start: " + err.Error())
		os.Exit(1)
	}
}

func run() error {
	switch {
	case *flagInit:
		return runInit()
	case *flagHashPassword:
		return runHashPassword()
	case *flagInstall:
		return runInstall()
	case *flagUninstall:
		return runUninstall()
	}
	return runServer()
}

func configPath() (string, error) {
	if *flagConfig != "" {
		return *flagConfig, nil
	}
	dir, err := config.ExeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, ".env"), nil
}

func runInit() error {
	path, err := configPath()
	if err != nil {
		return err
	}
	if err := writeStarterEnv(path); err != nil {
		return err
	}
	fmt.Printf("Wrote %s\nNext: run --hash-password and paste the result into SHUTDOWNER_PASSWORD_HASH.\n", path)
	return nil
}

// writeStarterEnv creates a .env with a fresh session secret. It refuses to
// overwrite, because regenerating the secret silently would sign every device
// out with no explanation.
func writeStarterEnv(path string) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s already exists; delete it first if you mean to regenerate it", path)
	}
	secret := make([]byte, 32)
	if _, err := rand.Read(secret); err != nil {
		return fmt.Errorf("generating a session secret: %w", err)
	}
	content := fmt.Sprintf(starterEnv, hex.EncodeToString(secret))
	return os.WriteFile(path, []byte(content), 0o600)
}

func runHashPassword() error {
	first, err := readSecret("Password: ")
	if err != nil {
		return err
	}
	if len(first) < minPasswordLength {
		return fmt.Errorf("the password must be at least %d characters: it is the only thing between the internet and your power button", minPasswordLength)
	}
	second, err := readSecret("Repeat:   ")
	if err != nil {
		return err
	}
	if first != second {
		return errors.New("the two passwords do not match")
	}

	hash, err := auth.HashPassword(first)
	if err != nil {
		return fmt.Errorf("hashing the password: %w", err)
	}
	fmt.Printf("\nPaste this line into your .env:\n\nSHUTDOWNER_PASSWORD_HASH=%s\n", hash)
	return nil
}

func runInstall() error {
	exe, err := os.Executable()
	if err != nil {
		return err
	}
	if err := winsvc.Install(exe); err != nil {
		return err
	}
	fmt.Printf("Installed and started the %s service.\n", winsvc.ServiceName)
	return nil
}

func runUninstall() error {
	if err := winsvc.Uninstall(); err != nil {
		return err
	}
	fmt.Printf("Removed the %s service.\n", winsvc.ServiceName)
	return nil
}

func runServer() error {
	cfg, err := config.Load(*flagConfig, *flagAllowPublicBind)
	if err != nil {
		return err
	}

	logger, closeLog, err := newLogger(cfg.LogFile, *flagConsole)
	if err != nil {
		return err
	}
	defer closeLog()

	var ctrl power.Controller = power.New()
	if *flagFakePower {
		logger.Warn("running with --fake-power: no real power action will be taken")
		ctrl = power.NewFake()
	}

	srv, err := web.New(web.Options{
		Sessions:     auth.NewSessionManager(cfg.SessionSecret, cfg.SessionTTL),
		Limiter:      auth.NewLimiter(auth.DefaultPerIPLimit, auth.DefaultGlobalLimit, auth.DefaultWindow),
		Actions:      action.New(ctrl, cfg.Delay),
		Power:        ctrl,
		Logger:       logger,
		PasswordHash: cfg.PasswordHash,
		DelaySeconds: int(cfg.Delay / time.Second),
	})
	if err != nil {
		return err
	}

	app := &App{
		logger: logger,
		http: &http.Server{
			Addr:    cfg.Listen,
			Handler: srv.Routes(),
			// The tunnel is the only client, but a slow-header or slow-body
			// attack would still tie up connections without these. WriteTimeout
			// is safe at 30s because no handler blocks: a power action is
			// executed by the action manager's timer goroutine, never inside a
			// request.
			ReadHeaderTimeout: 10 * time.Second,
			ReadTimeout:       20 * time.Second,
			WriteTimeout:      30 * time.Second,
			IdleTimeout:       120 * time.Second,
		},
	}

	logger.Info("starting",
		"listen", cfg.Listen,
		"delaySeconds", int(cfg.Delay/time.Second),
		"sessionTTL", cfg.SessionTTL.String())

	return winsvc.Run(logger, app.Start, app.Stop)
}

// newLogger returns a logger and a close function. A service has no console, so
// off --console everything goes to the rotating log file.
func newLogger(path string, console bool) (*slog.Logger, func(), error) {
	if console {
		h := slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo})
		return slog.New(h), func() {}, nil
	}
	w, err := logging.NewRotatingWriter(path, logging.DefaultMaxBytes, logging.DefaultKeep)
	if err != nil {
		return nil, nil, err
	}
	h := slog.NewJSONHandler(w, &slog.HandlerOptions{Level: slog.LevelInfo})
	return slog.New(h), func() { _ = w.Close() }, nil
}
